# Generated by Django 4.1.7 on 2023-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_producto_img_servicio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='img',
            field=models.ImageField(upload_to='servicios/'),
        ),
    ]
