# Generated by Django 4.2.5 on 2023-10-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrito',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
